### ISSUE TITLE
ld: library not found for -lerl_interface

### ISSUE THREAD

**Issue by wwhai** [klarna/brod#476]
ld: library not found for -lerl_interface:

**Comment by zmstone** [comment]
looks like you are compiling an older version brod on otp 23 or later.

could you be more specific?
* which Erlang/OTP version?
* which brod version ?

**Comment by wwhai** [comment]
> looks like you are compiling an older version brod on otp 23 or later.
> 
> could you be more specific?
> 
> * which Erlang/OTP version?
> * which brod version ?

1. OTP24 on windows WSL2
2. Brod master
